language: csharp
solution: ReqIFSharp.sln
install:
  - nuget restore ReqIFSharp.sln
  - nuget install NUnit.ConsoleRunner -Version 3.7.0 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release ReqIFSharp.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit-console.exe ./ReqIFSharp.Tests/bin/Release/ReqIFSharp.Tests.dll